# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# PROFILES
spring.profiles:
  active: # Comma-separated list of active profiles. Can be overridden by a command line switch.
#    - dev
  include: # Unconditionally activate the specified comma-separated list of profiles (or list of profiles if using YAML).

# ----------------------------------------
# DATA PROPERTIES
# ----------------------------------------
db:
  host: ${DB_SERVER_HOST:127.0.0.1}
  port: ${DB_SERVER_PORT:5432}
  name: ${DB_NAME:reactive}
  user: ${DB_USER:reactive}
  pass: ${DB_PASSWORD:reactive}

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource:
  driver-class-name: org.postgresql.Driver # Fully qualified name of the JDBC driver. Auto-detected based on the URL by default.
  url: jdbc:postgresql://${db.host}:${db.port}/${db.name} # JDBC URL of the name.
  username: ${db.user} # Login user of the name.
  password: ${db.pass} # Login pass of the name.

# FLYWAY
spring.flyway:
  enabled: true # Whether to enable flyway.
  locations: # Locations of migrations scripts. Can contain the special "{vendor}" placeholder to use vendor-specific locations.
    - classpath:db/migration

# ===================================================================
# Application specific properties
# ===================================================================

# application:
